CSV_COLUMNS:
  TBS_ATTRIBUTES: [trim, lower, no_null]
  FEATURE_ATTRIBUTES: [trim, lower, no_null]
  SECTION: [trim, upper, no_null]
#
CREATE_KEY_VALUE:
#
NO_DUPLICATE:
  DUP_1: [TBS_ATTRIBUTES]
#
CHECK_DOMAIN:
